- hosts: all
  become: yes
  become_method: sudo
  become_user: '{{ rhsm_username }}'
  become_pass: '{{ rhsm_password }}'

  tasks:
  - name: install the latest version of Apache
    yum:
      name: '*'
      state: latest

