###########################################################################
#  software-Update.yml
#--------------------------------------------------------------------------
# This playbook installs all available RPM updates on the inventory hosts.
#
#--------------------------------------------------------------------------
#
# Change History
# Date          Name           Version   Description
# 2021-03-02    Mark Davis     00.00     started new code
###########################################################################
---

###########################################################################
# Play 1 - Do updates for host
###########################################################################
- name: Play 1 - install updates on the Ansible controller
  hosts: all
  become: yes
  become_method: sudo
  become_user: '{{ rhsm_username }}'

#  vars:
#    run: false
#    reboot:false

  tasks:
  #########################################################################
  # Perform the updates
  #########################################################################
    - name: Install all available updates
      yum:
        name: "*"
        state: latest
        update_cache: true


